apiVersion: v1
kind: Config

clusters:
- cluster:
        server: https://192.168.99.108:8443
        certificate-authority: /root/ca.crt
  name: mycluster

contexts:
- context:
        cluster: mycluster
        user: aditya


users:
- name: aditya
  user:
     client-key: /root/client.key
     client-certificate: /root/client.crt
