apiVersion: v1 
kind: ReplicationController
metadata:
  name: myrc
  labels:
    country: IN
    env: prod

spec:
  replicas: 3
  selector:
    app: web

  template:
    metadata:
      name: mypod2
      labels:
        app: web
    spec:
      containers:
        - name: mycon
          image: vimal13/apache-webserver-php